
set(AMIGA_ASSEMBLER_NAME vasmm68k_mot)
set(AMIGA_LINKER_NAME vlink)

find_path(AMIGA_M68K_ASSEMBLER_PATH NAMES "${AMIGA_ASSEMBLER_NAME}" "${AMIGA_ASSEMBLER_NAME}.exe" CMAKE_FIND_ROOT_PATH_BOTH)

# Remove the <path>/bin part
get_filename_component(AMIGA_PATH_PREFIX ${AMIGA_M68K_ASSEMBLER_PATH} DIRECTORY)
set(AMIGA_OS_PATH_PREFIX "${AMIGA_PATH_PREFIX}/m68k-amigaos")
